name: APCGAN_AttuNet
channels: defaults
dependencies:
- python=3.8
- pandas>=1.0
- seaborn=0.11
- notebook
- scikit-learn>=1.0
- dload=0.6
- numpy=1.20.1
- requests=2.25.1
- scipy=1.6.2
- seaborn=0.11.1
- opencv-python
- pillow
- pyqt5
- tqdm
- pillow
- labelme

